name: Go-Build

on:
  push:
    branches:
      - "main"
    paths:
      - .github/workflows/**
      - cache/**
      - cleaner/**
      - config/**
      - database/**
      - discovery/**
      - interfaces/**
      - logger/**
      - middleware/**
      - testutils/**
      - utils/**
      - main.go
      - go.mod
  pull_request:
    branches:
      - "main"
  workflow_dispatch:


jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Build
        run: go build -ldflags="-w -s" -tags "http" -o metar-service-linux .

      - name: Test
        run: go test ./...