name: run unit tests

on:
  push:
    branches:
      - "main"
    paths:
      - .github/workflows/**
      - cache/**
      - cleaner/**
      - config/**
      - database/**
      - discovery/**
      - interfaces/**
      - logger/**
      - middleware/**
      - testutils/**
      - utils/**
      - main.go
      - go.mod
  pull_request:
    branches:
      - "main"


jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Test
        run: go test ./... -tags "permission event_bus" --count=1